"""
Alerts router — list security alerts generated by the detection engine.
"""

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.database import get_db
from app.models import Alert
from app.schemas import AlertOut

router = APIRouter(prefix="/api/alerts", tags=["Alerts"])


@router.get("/", response_model=list[AlertOut])
def list_alerts(
    severity: Optional[str] = Query(None, description="Filter by severity"),
    rule_name: Optional[str] = Query(None, description="Filter by rule name"),
    source_ip: Optional[str] = Query(None, description="Filter by source IP"),
    page: int = Query(1, ge=1),
    per_page: int = Query(50, ge=1, le=200),
    db: Session = Depends(get_db),
) -> list[AlertOut]:
    """Return paginated, filtered alerts."""
    query = db.query(Alert)

    if severity:
        query = query.filter(Alert.severity == severity)
    if rule_name:
        query = query.filter(Alert.rule_name == rule_name)
    if source_ip:
        query = query.filter(Alert.source_ip == source_ip)

    alerts = (
        query.order_by(Alert.created_at.desc())
        .offset((page - 1) * per_page)
        .limit(per_page)
        .all()
    )
    return [AlertOut.model_validate(a) for a in alerts]


@router.get("/stats")
def alert_stats(db: Session = Depends(get_db)) -> dict:
    """Return aggregate alert statistics for the dashboard."""
    total = db.query(func.count(Alert.id)).scalar() or 0
    critical = (
        db.query(func.count(Alert.id)).filter(Alert.severity == "critical").scalar() or 0
    )
    high = (
        db.query(func.count(Alert.id)).filter(Alert.severity == "high").scalar() or 0
    )
    medium = (
        db.query(func.count(Alert.id)).filter(Alert.severity == "medium").scalar() or 0
    )

    # Severity breakdown
    return {
        "total": total,
        "critical": critical,
        "high": high,
        "medium": medium,
        "low": total - critical - high - medium,
    }


@router.delete("/{alert_id}")
def delete_alert(alert_id: int, db: Session = Depends(get_db)) -> dict:
    """Delete a single alert (acknowledge / dismiss)."""
    alert = db.query(Alert).filter(Alert.id == alert_id).first()
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found.")
    db.delete(alert)
    db.commit()
    return {"detail": f"Alert {alert_id} deleted."}
