"""
SQLAlchemy ORM models for log events and security alerts.
"""

import json
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class LogEvent(Base):
    """A single parsed log line stored as a structured event."""

    __tablename__ = "log_events"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, nullable=False, index=True)
    source_ip: Mapped[str | None] = mapped_column(String(45), nullable=True, index=True)
    username: Mapped[str | None] = mapped_column(String(128), nullable=True)
    event_type: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    log_source: Mapped[str] = mapped_column(String(32), nullable=False)  # "auth" | "nginx"
    raw_line: Mapped[str] = mapped_column(Text, nullable=False)
    file_name: Mapped[str] = mapped_column(String(256), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:
        return (
            f"<LogEvent id={self.id} type={self.event_type} "
            f"ip={self.source_ip} ts={self.timestamp}>"
        )


class Alert(Base):
    """A security alert generated by a detection rule."""

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    rule_name: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(16), nullable=False)  # low, medium, high, critical
    source_ip: Mapped[str] = mapped_column(String(45), nullable=False, index=True)
    event_count: Mapped[int] = mapped_column(Integer, nullable=False)
    first_seen: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    last_seen: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    # JSON-encoded list of unique usernames targeted by this attacker IP.
    # Example: '["root", "admin", "ubuntu"]'
    # Nullable for backward compatibility with alerts created before this column.
    usernames: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )

    # ── Helpers ──────────────────────────────────────────────────────────

    def get_usernames(self) -> list[str]:
        """Decode the JSON-stored usernames list.  Returns [] on missing/bad data."""
        if not self.usernames:
            return []
        try:
            return json.loads(self.usernames)
        except (json.JSONDecodeError, TypeError):
            return []

    @staticmethod
    def encode_usernames(names: list[str]) -> str:
        """JSON-encode a list of usernames for storage."""
        return json.dumps(sorted(set(names)))

    def __repr__(self) -> str:
        return (
            f"<Alert id={self.id} rule={self.rule_name} "
            f"sev={self.severity} ip={self.source_ip}>"
        )
